version: '3.8'

services:
  web:
    build: .
    container_name: nginx_https
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./html:/usr/share/nginx/html:ro
